In [1]:
#Task: Create a list of 5 integers and demonstrate: append, extend, insert, remove, pop, clear, index, count, sort, reverse.
def ex1_list_operations():
    nums = [5, 2, 9, 1, 7]
    print("Original:", nums)

    nums.append(11)
    print("append(11):", nums)

    nums.extend([3, 4])
    print("extend([3,4]):", nums)

    nums.insert(2, 0)   # insert 0 at index 2
    print("insert(2,0):", nums)

    nums.remove(9)      # remove first occurrence of 9
    print("remove(9):", nums)

    popped = nums.pop() # pop last
    print("pop():", nums, "popped:", popped)

    idx7 = nums.index(7) if 7 in nums else -1
    print("index(7):", idx7)

    cnt2 = nums.count(2)
    print("count(2):", cnt2)

    nums.sort()
    print("sort():", nums)

    nums.reverse()
    print("reverse():", nums)

    nums.clear()
    print("clear():", nums)

# Run example
ex1_list_operations()


Original: [5, 2, 9, 1, 7]
append(11): [5, 2, 9, 1, 7, 11]
extend([3,4]): [5, 2, 9, 1, 7, 11, 3, 4]
insert(2,0): [5, 2, 0, 9, 1, 7, 11, 3, 4]
remove(9): [5, 2, 0, 1, 7, 11, 3, 4]
pop(): [5, 2, 0, 1, 7, 11, 3] popped: 4
index(7): 4
count(2): 1
sort(): [0, 1, 2, 3, 5, 7, 11]
reverse(): [11, 7, 5, 3, 2, 1, 0]
clear(): []


In [2]:
# Exercise 2: Tuple Example

# Creating a tuple with 3 student names
students = ("Ravi", "Anita", "Kiran")

# Trying to change the second name in the tuple
try:
    students[1] = "Sita"   # Tuples do not support item assignment
except TypeError as e:
    print("Error:", e)

# Printing the tuple to show it remains unchanged
print("Final tuple:", students)

# Explanation:
# Tuples in Python are immutable, meaning their elements cannot be changed,
# added, or removed after creation. Attempting to modify a tuple element
# raises a TypeError.

Error: 'tuple' object does not support item assignment
Final tuple: ('Ravi', 'Anita', 'Kiran')


In [3]:
#Task: Create a set of integers with duplicates. Print and explain.
values = [1, 2, 3, 2, 4, 1, 5]
s = set(values)
print("Original list:", values)
print("Set (duplicates removed):", s)
#Explanation: Sets store unique items; duplicates from the list are removed. Order is not guaranteed.

Original list: [1, 2, 3, 2, 4, 1, 5]
Set (duplicates removed): {1, 2, 3, 4, 5}


In [4]:
# Create dictionary with keys 'name', 'age', 'city'. Update age and add 'email
# Exercise 4
person = {'name': 'Asha', 'age': 22, 'city': 'Hyderabad'}
print("Original:", person)

# Update age
person['age'] = 23

# Add email
person['email'] = 'asha@example.com'

print("Updated:", person)
#Explanation: Dictionaries are mutable mappings; you can update and add keys.

Original: {'name': 'Asha', 'age': 22, 'city': 'Hyderabad'}
Updated: {'name': 'Asha', 'age': 23, 'city': 'Hyderabad', 'email': 'asha@example.com'}


In [5]:
#Task: Check if a person is eligible to vote (age ≥ 18). Use age variable.
# Exercise 5
def ex5_voting_eligibility(age):
    print("Age:", age)
    if age >= 18:
        print("Eligible to vote.")
    else:
        print("Not eligible to vote.")

# Examples
ex5_voting_eligibility(17)
ex5_voting_eligibility(18)


Age: 17
Not eligible to vote.
Age: 18
Eligible to vote.


In [6]:
#Grade from marks
#Task: Given marks, print grade:
#90+ → 'A'
#75–89 → 'B'
#50–74 → 'C'
#Below 50 → 'Fail'
# Exercise 6
def ex6_grade_from_marks(marks):
    print("Marks:", marks)
    if marks >= 90:
        print("Grade: A")
    elif marks >= 75:
        print("Grade: B")
    elif marks >= 50:
        print("Grade: C")
    else:
        print("Grade: Fail")

# Examples
ex6_grade_from_marks(92)
ex6_grade_from_marks(80)
ex6_grade_from_marks(60)
ex6_grade_from_marks(45)


Marks: 92
Grade: A
Marks: 80
Grade: B
Marks: 60
Grade: C
Marks: 45
Grade: Fail


In [7]:
# Task: Given a number, check if it's positive, and if so check if it's even. If not positive, print zero or negative.
def ex7_positive_even_check(n):
    print("Number:", n)
    if n > 0:
        print("Positive number.")
        if n % 2 == 0:
            print("Also even.")
        else:
            print("Also odd.")
    elif n == 0:
        print("Zero.")
    else:
        print("Negative number.")

# Examples
ex7_positive_even_check(10)
ex7_positive_even_check(7)
ex7_positive_even_check(0)
ex7_positive_even_check(-5)

Number: 10
Positive number.
Also even.
Number: 7
Positive number.
Also odd.
Number: 0
Zero.
Number: -5
Negative number.


In [8]:
#Numpy arrays (scalar, 1D, 2D)
#Task: Create:
#Scalar using np.array(5)
#1D array 1..5
#2D array (2x3) with values 10–60 step 10
# Exercise 8
import numpy as np

# Scalar
scalar = np.array(5)
print("Scalar:", scalar, "shape:", scalar.shape)

# 1D array 1..5
arr1d = np.array([1,2,3,4,5])
print("1D:", arr1d, "shape:", arr1d.shape)

# 2D 2x3 values 10..60
arr2d = np.array([[10,20,30],[40,50,60]])
print("2D:\n", arr2d, "shape:", arr2d.shape)


Scalar: 5 shape: ()
1D: [1 2 3 4 5] shape: (5,)
2D:
 [[10 20 30]
 [40 50 60]] shape: (2, 3)


In [9]:
#Task: Generate 4×4 array of random ints between 0 and 100.
import numpy as np

np.random.seed(0)  # makes the random numbers repeatable
rnd = np.random.randint(0, 101, size=(4, 4))
print(rnd)

[[44 47 64 67]
 [67  9 83 21]
 [36 87 70 88]
 [88 12 58 65]]


In [10]:
#Task: Create 3×3 numpy array and convert to DataFrame with column names.
# Exercise 10
import pandas as pd
arr = np.arange(1,10).reshape(3,3)  # values 1..9
df = pd.DataFrame(arr, columns=['A','B','C'])
print("DataFrame:\n", df)


DataFrame:
    A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


In [11]:
#Pandas DataFrame (10 rows): .info(), .describe(), select/drop, fill missing Salary with mean, remove duplicates

#Task: Create a DataFrame with 10 rows columns: Name, Age, City, Salary. Then do the operations.
# Exercise 11
import pandas as pd
import numpy as np

data = {
    'Name': ['A','B','C','D','E','F','G','H','I','J'],
    'Age' : [25,30,22,28,35,30,22,28,29,35],
    'City': ['Hyd','Hyd','Bangalore','Mumbai','Delhi','Hyd','Bangalore','Mumbai','Delhi','Hyd'],
    # include some missing salaries and duplicates intentionally
    'Salary': [50000, 60000, None, 55000, 70000, 60000, None, 55000, 65000, 60000]
}
df = pd.DataFrame(data)
print("Initial DataFrame:\n", df, "\n")

# .info() and .describe()
print("Info:")
df.info()
print("\nDescribe:")
print(df.describe(include='all'))

# Select Name and City
print("\nSelected columns (Name, City):\n", df[['Name','City']])

# Drop City
df_no_city = df.drop(columns=['City'])
print("\nAfter dropping City:\n", df_no_city)

# Fill missing Salary with mean
salary_mean = df['Salary'].mean(skipna=True)
df['Salary'] = df['Salary'].fillna(salary_mean)
print(f"\nAfter filling missing Salary with mean ({salary_mean:.2f}):\n", df)

# Remove duplicate rows
df_no_duplicates = df.drop_duplicates()
print("\nAfter removing duplicates:\n", df_no_duplicates)

Initial DataFrame:
   Name  Age       City   Salary
0    A   25        Hyd  50000.0
1    B   30        Hyd  60000.0
2    C   22  Bangalore      NaN
3    D   28     Mumbai  55000.0
4    E   35      Delhi  70000.0
5    F   30        Hyd  60000.0
6    G   22  Bangalore      NaN
7    H   28     Mumbai  55000.0
8    I   29      Delhi  65000.0
9    J   35        Hyd  60000.0 

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes

Describe:
       Name        Age City        Salary
count    10  10.000000   10      8.000000
unique   10        NaN    4           NaN
top       A        NaN  Hyd           NaN
freq      1        NaN    4           NaN
mean    N